"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-04-20 01:52:43.795012

"""
import hashlib
from typing import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('reporting_period_label', sa.String(), nullable=True),
    sa.Column('reporting_period_type', sa.String(), nullable=True),
    sa.Column('source_document_type', sa.String(), nullable=True),
    sa.Column('industry_code', sa.String(), nullable=True),
    sa.Column('industry_sector', sa.String(), nullable=True),
    sa.Column('scope1_co2e_tonnes', sa.Float(), nullable=True),
    sa.Column('scope2_co2e_tonnes', sa.Float(), nullable=True),
    sa.Column('scope3_co2e_tonnes', sa.Float(), nullable=True),
    sa.Column('energy_consumption_mwh', sa.Float(), nullable=True),
    sa.Column('renewable_energy_pct', sa.Float(), nullable=True),
    sa.Column('water_usage_m3', sa.Float(), nullable=True),
    sa.Column('waste_recycled_pct', sa.Float(), nullable=True),
    sa.Column('total_revenue_eur', sa.Float(), nullable=True),
    sa.Column('taxonomy_aligned_revenue_pct', sa.Float(), nullable=True),
    sa.Column('total_capex_eur', sa.Float(), nullable=True),
    sa.Column('taxonomy_aligned_capex_pct', sa.Float(), nullable=True),
    sa.Column('total_employees', sa.Integer(), nullable=True),
    sa.Column('female_pct', sa.Float(), nullable=True),
    sa.Column('primary_activities', sa.Text(), nullable=True),
    sa.Column('pdf_filename', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('source_doc_key', sa.String(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('deletion_requested', sa.Boolean(), nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name', 'report_year', 'source_doc_key', name='uq_company_reports_source_key')
    )
    with op.batch_alter_table('company_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_reports_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_reports_industry_code'), ['industry_code'], unique=False)

    op.create_table('industry_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_code', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=True),
    sa.Column('p25', sa.Float(), nullable=True),
    sa.Column('p50', sa.Float(), nullable=True),
    sa.Column('p75', sa.Float(), nullable=True),
    sa.Column('p90', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_code', 'metric_name', 'period_year', name='uq_benchmark_key')
    )
    with op.batch_alter_table('industry_benchmarks', schema=None) as batch_op:
        batch_op.create_index('ix_benchmark_lookup', ['industry_code', 'period_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_industry_benchmarks_industry_code'), ['industry_code'], unique=False)

    op.create_table('extraction_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_report_id', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('run_kind', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_runs_company_report_id'), ['company_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_runs_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_runs_run_kind'), ['run_kind'], unique=False)

    op.create_table('framework_analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.String(), nullable=False),
    sa.Column('framework_name', sa.String(), nullable=False),
    sa.Column('framework_version', sa.String(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('result_payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name', 'report_year', 'framework_id', 'framework_version', 'payload_hash', name='uq_framework_analysis_payload')
    )
    with op.batch_alter_table('framework_analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_framework_analysis_results_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_analysis_results_framework_id'), ['framework_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_analysis_results_payload_hash'), ['payload_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_analysis_results_report_year'), ['report_year'], unique=False)

    op.create_table('pending_disclosures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('extracted_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name', 'report_year', 'source_url', name='uq_pending_disclosures_source')
    )
    with op.batch_alter_table('pending_disclosures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_disclosures_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_disclosures_report_year'), ['report_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_disclosures_status'), ['status'], unique=False)

    bind = op.get_bind()

    # Keep parity with legacy runtime schema helpers: explicit unique indexes.
    if bind.dialect.name == "sqlite":
        op.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_company_reports_source_key
            ON company_reports (company_name, report_year, source_doc_key)
            """
        )
        op.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_framework_analysis_payload
            ON framework_analysis_results (company_name, report_year, framework_id, framework_version, payload_hash)
            """
        )
        op.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_pending_disclosures_source
            ON pending_disclosures (company_name, report_year, source_url)
            """
        )

    # Legacy helper backfills are retained for deterministic bootstrap parity.
    op.execute(
        """
        UPDATE company_reports
        SET source_doc_key = CASE
            WHEN file_hash IS NOT NULL AND trim(file_hash) != ''
                THEN 'file_hash:' || lower(trim(file_hash))
            WHEN source_url IS NOT NULL AND trim(source_url) != ''
                THEN 'source_url:' || lower(trim(source_url))
                    || '|type:' || lower(COALESCE(source_document_type, ''))
            WHEN pdf_filename IS NOT NULL AND trim(pdf_filename) != ''
                THEN 'pdf_filename:' || lower(trim(pdf_filename))
                    || '|type:' || lower(COALESCE(source_document_type, ''))
            ELSE 'period:' || lower(COALESCE(source_document_type, ''))
                || '|label:' || lower(COALESCE(reporting_period_label, CAST(report_year AS TEXT)))
        END
        WHERE (source_doc_key IS NULL OR trim(source_doc_key) = '')
          AND EXISTS (SELECT 1 FROM company_reports LIMIT 1)
        """
    )
    op.execute(
        """
        DELETE FROM company_reports
        WHERE id IN (
            SELECT id FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY company_name, report_year, source_doc_key
                           ORDER BY updated_at DESC, created_at DESC, id DESC
                       ) AS rn
                FROM company_reports
                WHERE source_doc_key IS NOT NULL AND trim(source_doc_key) != ''
            ) dedup
            WHERE dedup.rn > 1
        )
        AND EXISTS (SELECT 1 FROM company_reports LIMIT 1)
        """
    )
    rows = bind.execute(
        sa.text(
            """
            SELECT id, result_payload, payload_hash
            FROM framework_analysis_results
            WHERE payload_hash IS NULL OR trim(payload_hash) = ''
            """
        )
    ).mappings().all()
    for row in rows:
        payload = row["result_payload"] or ""
        payload_hash = hashlib.sha256(payload.encode("utf-8")).hexdigest()
        bind.execute(
            sa.text(
                """
                UPDATE framework_analysis_results
                SET payload_hash = :payload_hash
                WHERE id = :id
                """
            ),
            {"id": row["id"], "payload_hash": payload_hash},
        )
    op.execute(
        """
        DELETE FROM framework_analysis_results
        WHERE id IN (
            SELECT id FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY company_name, report_year, framework_id, framework_version, payload_hash
                           ORDER BY created_at DESC, id DESC
                       ) AS rn
                FROM framework_analysis_results
                WHERE payload_hash IS NOT NULL AND trim(payload_hash) != ''
            ) dedup
            WHERE dedup.rn > 1
        )
        AND EXISTS (SELECT 1 FROM framework_analysis_results LIMIT 1)
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_disclosures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_disclosures_status'))
        batch_op.drop_index(batch_op.f('ix_pending_disclosures_report_year'))
        batch_op.drop_index(batch_op.f('ix_pending_disclosures_company_name'))

    op.drop_table('pending_disclosures')
    with op.batch_alter_table('framework_analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_framework_analysis_results_report_year'))
        batch_op.drop_index(batch_op.f('ix_framework_analysis_results_payload_hash'))
        batch_op.drop_index(batch_op.f('ix_framework_analysis_results_framework_id'))
        batch_op.drop_index(batch_op.f('ix_framework_analysis_results_company_name'))

    op.drop_table('framework_analysis_results')
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_runs_run_kind'))
        batch_op.drop_index(batch_op.f('ix_extraction_runs_file_hash'))
        batch_op.drop_index(batch_op.f('ix_extraction_runs_company_report_id'))

    op.drop_table('extraction_runs')
    with op.batch_alter_table('industry_benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_industry_benchmarks_industry_code'))
        batch_op.drop_index('ix_benchmark_lookup')

    op.drop_table('industry_benchmarks')
    with op.batch_alter_table('company_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_reports_industry_code'))
        batch_op.drop_index(batch_op.f('ix_company_reports_company_name'))

    op.drop_table('company_reports')
    # ### end Alembic commands ###
