import type { CompanyProfile, IndustryBenchmarksResponse } from '../src/lib/types'

export function buildEvidenceCompanyProfileFixture(): CompanyProfile {
  const renewableEvidence = {
    metric: 'renewable_energy_pct',
    source: 'Acme Sustainability Fact Sheet 2024',
    document_title: 'Acme Sustainability Fact Sheet 2024',
    document_short_ref: 'Fact Sheet 2024',
    page: 5,
    snippet:
      'Renewable electricity share reached 49.1% in FY 2024, up from 44.0% last year. Procurement improvements across Germany sites drove the increase and the figure was validated during manual QA.',
    source_type: 'manual_case',
    source_url: 'https://example.com/acme-factsheet-2024.pdf',
    file_hash: 'fixture-hash-renewable',
    reporting_period_label: 'FY 2024',
    extraction_method: 'manual_entry',
    confidence: 0.87,
    framework: 'Evidence-backed',
  }

  const latestMetrics = {
    company_name: 'Acme Corp',
    report_year: 2024,
    reporting_period_label: 'FY 2024',
    reporting_period_type: 'annual',
    source_document_type: 'annual_report',
    industry_code: 'DE-123',
    industry_sector: 'Industrial machinery',
    scope1_co2e_tonnes: 120,
    scope2_co2e_tonnes: 80,
    scope3_co2e_tonnes: 450,
    energy_consumption_mwh: 1200,
    renewable_energy_pct: 49.1,
    water_usage_m3: 3000,
    waste_recycled_pct: 66.2,
    total_revenue_eur: 250000000,
    taxonomy_aligned_revenue_pct: 18.4,
    total_capex_eur: 52000000,
    taxonomy_aligned_capex_pct: 12.7,
    total_employees: 4200,
    female_pct: 33.3,
    primary_activities: ['machinery manufacturing'],
    evidence_summary: [renewableEvidence],
  }

  return {
    company_name: 'Acme Corp',
    years_available: [2022, 2023, 2024],
    latest_year: 2024,
    latest_period: {
      report_year: 2024,
      reporting_period_label: 'FY 2024',
      reporting_period_type: 'annual',
      source_document_type: 'annual_report',
      industry_code: 'DE-123',
      industry_sector: 'Industrial machinery',
      period: {
        period_id: 'period-2024',
        label: 'FY 2024',
        type: 'annual',
        source_document_type: 'annual_report',
        legacy_report_year: 2024,
      },
      framework_metadata: [],
    },
    latest_metrics: latestMetrics,
    trend: [
      {
        year: 2022,
        scope1: 130,
        scope2: 90,
        scope3: 470,
        renewable_pct: 40.1,
        taxonomy_aligned_revenue_pct: 16.5,
        taxonomy_aligned_capex_pct: 11.1,
        female_pct: 32.8,
      },
      {
        year: 2023,
        scope1: 126,
        scope2: 84,
        scope3: 460,
        renewable_pct: 44.0,
        taxonomy_aligned_revenue_pct: 17.1,
        taxonomy_aligned_capex_pct: 11.8,
        female_pct: 33.0,
      },
      {
        year: 2024,
        scope1: 120,
        scope2: 80,
        scope3: 450,
        renewable_pct: 49.1,
        taxonomy_aligned_revenue_pct: 18.4,
        taxonomy_aligned_capex_pct: 12.7,
        female_pct: 33.3,
      },
    ],
    periods: [
      {
        report_year: 2024,
        reporting_period_label: 'FY 2024',
        reporting_period_type: 'annual',
        source_document_type: 'annual_report',
        industry_code: 'DE-123',
        industry_sector: 'Industrial machinery',
        period: {
          period_id: 'period-2024',
          label: 'FY 2024',
          type: 'annual',
          source_document_type: 'annual_report',
          legacy_report_year: 2024,
        },
        source_url: 'https://example.com/2024.pdf',
        downloaded_at: '2026-04-16T10:00:00Z',
        evidence_anchors: [renewableEvidence],
        framework_metadata: [],
        source_documents: [
          {
            source_id: 'db:77',
            source_document_type: 'manual_case',
            reporting_period_label: 'FY 2024',
            reporting_period_type: 'annual',
            source_url: 'https://example.com/acme-factsheet-2024.pdf',
            file_hash: 'fixture-hash-renewable',
            pdf_filename: 'acme-factsheet-2024.pdf',
            downloaded_at: '2026-04-16T10:00:00Z',
            evidence_anchors: [renewableEvidence],
          },
        ],
        merged_result: {
          company_name: 'Acme Corp',
          report_year: 2024,
          merged_metrics: latestMetrics,
          metrics: {},
          source_count: 1,
        },
      },
    ],
    framework_metadata: [],
    framework_scores: [],
    framework_results: [],
    evidence_summary: [renewableEvidence],
    data_quality_summary: {
      total_key_metrics_count: 5,
      present_metrics_count: 3,
      present_metrics: [
        'scope1_co2e_tonnes',
        'renewable_energy_pct',
        'taxonomy_aligned_revenue_pct',
      ],
      missing_metrics: ['scope2_co2e_tonnes', 'total_employees'],
      completion_percentage: 60,
      readiness_label: 'usable',
    },
    identity_provenance_summary: {
      canonical_company_name: 'Acme Corp',
      requested_company_name: 'Acme Corp',
      has_alias_consolidation: false,
      consolidated_aliases: [],
      latest_source_document_type: 'annual_report',
      source_priority_preview: null,
      merge_priority_preview: null,
    },
    latest_sources: [
      {
        source_id: 'db:77',
        source_document_type: 'manual_case',
        reporting_period_label: 'FY 2024',
        reporting_period_type: 'annual',
        source_url: 'https://example.com/acme-factsheet-2024.pdf',
        file_hash: 'fixture-hash-renewable',
        pdf_filename: 'acme-factsheet-2024.pdf',
        downloaded_at: '2026-04-16T10:00:00Z',
        evidence_anchors: [renewableEvidence],
      },
    ],
    latest_merged_result: {
      company_name: 'Acme Corp',
      report_year: 2024,
      merged_metrics: latestMetrics,
      metrics: {},
      source_count: 1,
    },
  }
}

export function buildEvidenceBenchmarksFixture(): IndustryBenchmarksResponse {
  return {
    industry_code: 'DE-123',
    metrics: [
      {
        metric_name: 'renewable_energy_pct',
        period_year: 2024,
        p10: 28,
        p25: 34,
        p50: 39,
        p75: 45,
        p90: 52,
        sample_size: 12,
        computed_at: '2026-04-16T10:00:00Z',
      },
      {
        metric_name: 'scope1_co2e_tonnes',
        period_year: 2024,
        p10: 90,
        p25: 110,
        p50: 140,
        p75: 180,
        p90: 220,
        sample_size: 12,
        computed_at: '2026-04-16T10:00:00Z',
      },
    ],
  }
}
