#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FRONTEND_DIR="$ROOT_DIR/frontend"
OPENAPI_URL="${OPENAPI_URL:-http://127.0.0.1:8000/openapi.json}"
OUTPUT_FILE="$FRONTEND_DIR/src/lib/types.ts"
TMP_DIR="$(mktemp -d)"
SCHEMA_FILE="$TMP_DIR/openapi.json"
GENERATED_FILE="$TMP_DIR/types.generated.ts"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

if [[ ! -x "$FRONTEND_DIR/node_modules/.bin/openapi-typescript" ]]; then
  echo "error: frontend dependencies are missing; run 'cd frontend && npm install' first." >&2
  exit 1
fi

curl -fsSL "$OPENAPI_URL" -o "$SCHEMA_FILE"
"$FRONTEND_DIR/node_modules/.bin/openapi-typescript" "$SCHEMA_FILE" -o "$GENERATED_FILE"

cat >"$OUTPUT_FILE" <<'EOF'
// This file is auto-generated by scripts/gen-types.sh from the backend OpenAPI schema.
// Do not edit by hand. Run `npm run gen:types` from frontend/ after starting the backend.

EOF
cat "$GENERATED_FILE" >>"$OUTPUT_FILE"
cat >>"$OUTPUT_FILE" <<'EOF'

// Frontend compatibility layer.
// The raw OpenAPI types above are the source of truth; these exports preserve the
// existing frontend import surface while the backend gradually adopts richer
// response_model coverage for every route.
export interface EvidenceAnchor {
  metric: string | null
  source: string | null
  page: string | number | null
  page_number?: number | null
  snippet: string | null
  document_short_ref?: string | null
  document_title?: string | null
  framework?: string | null
  reporting_period_label?: string | null
  period_label?: string | null
  extraction_method?: string | null
  confidence?: string | null
  confidence_score?: number | null
  source_type?: string | null
  source_url?: string | null
  file_hash?: string | null
}

export interface CompanyESGData {
  company_name: string
  report_year: number
  reporting_period_label?: string | null
  reporting_period_type?: string | null
  source_document_type?: string | null
  industry_code?: string | null
  industry_sector?: string | null
  scope1_co2e_tonnes: number | null
  scope2_co2e_tonnes: number | null
  scope3_co2e_tonnes: number | null
  energy_consumption_mwh: number | null
  renewable_energy_pct: number | null
  water_usage_m3: number | null
  waste_recycled_pct: number | null
  total_revenue_eur: number | null
  taxonomy_aligned_revenue_pct: number | null
  total_capex_eur: number | null
  taxonomy_aligned_capex_pct: number | null
  total_employees: number | null
  female_pct: number | null
  primary_activities: string[]
  evidence_summary?: EvidenceAnchor[]
}

export interface ManualReportInput extends CompanyESGData {
  source_url?: string | null
}

export type AuditTrailRow = components["schemas"]["AuditTrailRow"]
export type TaxonomyScoreResult = components["schemas"]["TaxonomyScoreResult"]
export type LCOEInput = components["schemas"]["LCOEInput"]
export type LCOEResult = components["schemas"]["LCOEResult"]
export type SensitivityResult = components["schemas"]["SensitivityResult"]
export type DimensionScore = components["schemas"]["DimensionScore"]
export type FrameworkScoreResult = components["schemas"]["FrameworkScoreResult"]
export type MultiFrameworkReport = components["schemas"]["MultiFrameworkReport"]
export type TaxonomyActivity =
  paths["/taxonomy/activities"]["get"]["responses"]["200"]["content"]["application/json"][number]

export interface FrameworkMetadata {
  analysis_result_id: number
  framework_id: string
  framework: string
  framework_version: string
  report_year: number
  stored_at: string | null
}

export interface BatchJobItem {
  job_id: string
  filename: string
  status: 'queued' | 'processing' | 'completed' | 'failed'
  error: string | null
  result: CompanyESGData | null
  created_at: string
  started_at: string | null
  finished_at: string | null
  duration_seconds: number | null
}

export interface BatchStatusResponse {
  batch_id: string
  total_jobs: number
  queued_jobs: number
  running_jobs: number
  completed_jobs: number
  failed_jobs: number
  progress_pct: number
  jobs: BatchJobItem[]
}

export interface DashboardStats {
  total_companies: number
  avg_taxonomy_aligned: number
  avg_renewable_pct: number
  yearly_trend: Array<{ year: number; count: number }>
  top_emitters: Array<{ company: string; year: number; scope1: number }>
  bottom_emitters: Array<{ company: string; year: number; scope1: number }>
  coverage_rates: Record<string, number>
}

export interface IndustryBenchmarkMetric {
  metric_name: string
  period_year: number
  p10: number | null
  p25: number | null
  p50: number | null
  p75: number | null
  p90: number | null
  sample_size: number
  computed_at: string | null
}

export interface IndustryBenchmarksResponse {
  industry_code: string
  metrics: IndustryBenchmarkMetric[]
}

export interface CompanyByIndustryEntry {
  company_name: string
  report_year: number | null
  industry_code: string | null
  industry_sector: string | null
  metrics: Record<string, number | null>
}

export interface CompaniesByIndustryResponse {
  industry_code: string
  company_count: number
  companies: CompanyByIndustryEntry[]
}

export interface BenchmarkRecomputeResponse {
  industries: number
  metric_rows: number
}

export interface CompanyNormalizedPeriod {
  period_id: string
  label: string
  type: string
  source_document_type: string | null
  legacy_report_year: number
}

export interface CompanySourceDocument {
  source_id: string
  source_document_type: string | null
  reporting_period_label: string | null
  reporting_period_type: string | null
  source_url: string | null
  file_hash: string | null
  pdf_filename: string | null
  downloaded_at: string | null
  evidence_anchors: EvidenceAnchor[]
}

export interface MergeMetricCandidate {
  source_id: string
  source_document_type: string | null
  source_url: string | null
  reporting_period_label: string | null
  priority_rank: number
  value: string | number | string[] | null
}

export interface MergedMetricResult {
  metric: string
  chosen_value: string | number | string[] | null
  candidate_values: MergeMetricCandidate[]
  chosen_source: string | null
  chosen_source_document_type: string | null
  merge_reason: string
  conflict_detected: boolean
}

export interface CompanyMergedResult {
  company_name: string
  report_year: number
  merged_metrics: CompanyESGData
  metrics: Record<string, MergedMetricResult>
  source_count: number
}

export interface CompanyHistoryPeriod {
  report_year: number
  reporting_period_label: string
  reporting_period_type: string
  source_document_type: string | null
  industry_code?: string | null
  industry_sector?: string | null
  period: CompanyNormalizedPeriod
  source_url: string | null
  downloaded_at: string | null
  evidence_anchors: EvidenceAnchor[]
  framework_metadata: FrameworkMetadata[]
  source_documents: CompanySourceDocument[]
  merged_result: CompanyMergedResult
}

export interface CompanyProfileLatestPeriod {
  report_year: number
  reporting_period_label: string
  reporting_period_type: string
  source_document_type: string | null
  industry_code?: string | null
  industry_sector?: string | null
  period: CompanyNormalizedPeriod
  framework_metadata: FrameworkMetadata[]
}

export interface CompanyHistoryResponse {
  company_name: string
  periods: CompanyHistoryPeriod[]
  trend: CompanyTrendPoint[]
  framework_metadata: FrameworkMetadata[]
}

export interface CompanyTrendPoint {
  year: number
  scope1: number | null
  scope2: number | null
  scope3: number | null
  renewable_pct: number | null
  taxonomy_aligned_revenue_pct: number | null
  taxonomy_aligned_capex_pct: number | null
  female_pct: number | null
}

export interface CompanyDataQualitySummary {
  total_key_metrics_count: number
  present_metrics_count: number
  present_metrics: string[]
  missing_metrics: string[]
  completion_percentage: number
  readiness_label: 'draft' | 'usable' | 'showcase-ready'
}

export interface CompanyIdentityProvenanceSummary {
  canonical_company_name: string
  requested_company_name: string
  has_alias_consolidation: boolean
  consolidated_aliases: string[]
  latest_source_document_type: string | null
  source_priority_preview: string | null
  merge_priority_preview: string | null
}

export interface CompanyNarrativeSummary {
  snapshot: {
    periods_count: number
    years_count: number
    latest_year: number
    framework_count: number
    readiness_label: 'draft' | 'usable' | 'showcase-ready'
  }
  has_previous_period: boolean
  previous_year: number | null
  improved_metrics: string[]
  weakened_metrics: string[]
  stable_metrics: string[]
  disclosure_strength_metrics: string[]
  disclosure_gap_metrics: string[]
}

export interface CompanyProfile {
  company_name: string
  years_available: number[]
  latest_year: number
  latest_period: CompanyProfileLatestPeriod
  latest_metrics: CompanyESGData
  trend: CompanyTrendPoint[]
  periods: CompanyHistoryPeriod[]
  framework_metadata?: FrameworkMetadata[]
  framework_scores?: FrameworkScoreResult[]
  framework_results: Array<FrameworkScoreResult & { analysis_result_id?: number; stored_at?: string | null }>
  evidence_summary: EvidenceAnchor[]
  evidence_anchors?: EvidenceAnchor[]
  data_quality_summary: CompanyDataQualitySummary
  narrative_summary?: CompanyNarrativeSummary
  identity_provenance_summary?: CompanyIdentityProvenanceSummary
  latest_sources: CompanySourceDocument[]
  latest_merged_result: CompanyMergedResult
}

export interface RegionalGroup {
  region: string
  avg_score: number
  avg_grade: string
  strongest_area: string
  weakest_area: string
  frameworks: FrameworkScoreResult[]
}

export interface DimensionCrossMatrix {
  dimension_name: string
  eu_requirement: string
  cn_requirement: string
  us_requirement: string
  eu_score: number | null
  cn_score: number | null
  us_score: number | null
  gap_analysis: string
}

export interface RegionalComparisonReport {
  company_name: string
  report_year: number
  regional_groups: RegionalGroup[]
  cross_matrix: DimensionCrossMatrix[]
  compliance_priority: string[]
  overall_readiness: string
  key_insights: string[]
}
EOF

echo "Generated $OUTPUT_FILE from $OPENAPI_URL"
